### ISSUE TITLE
Should this Apache config be moved into the cap repository?

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/cihm-public-cap#2]
For other containers we have put the Apache config alongside the application container.  Should this be done for CAP?

If so a ticket can be created there to move Apache config (a cleaner config would be created) and this repository can be archived.

**Comment by SaschaAdler** [comment]
I don't see why CAP should be any different from the rest of our containers, and its complexity is only likely to decrease over time.

**Comment by RussellMcOrmond** [comment]
I created the new ticket, so closing this one.
